services:
  paruparo:
    build:
      context: .
    container_name: paruparo-service
    ports:
      - "8111:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - postgresql
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: paruparo-mongodb
    environment:
      MONGO_INITDB_DATABASE: mongodb
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "27111:27017"

  postgresql:
    image: postgres:15
    container_name: paruparo-postgresql
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdb
    ports:
      - "5111:5432"

volumes:
  paruparo-postgresql:
    driver: local
  paruparo-mongodb:
    driver: local
